# Generated by Django 4.1.1 on 2023-03-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=150, verbose_name='Характеристика товару')),
            ],
            options={
                'verbose_name': 'Характеристика товару',
                'verbose_name_plural': 'Характеристики товару',
            },
        ),
        migrations.CreateModel(
            name='ProductsBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default=None, max_length=200, verbose_name='Бренди')),
            ],
            options={
                'verbose_name': 'Бренди',
                'verbose_name_plural': 'Бренди',
            },
        ),
        migrations.CreateModel(
            name='ProductsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товару',
            },
        ),
        migrations.CreateModel(
            name='ValueProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, verbose_name='Дані про характеристику товару')),
            ],
            options={
                'verbose_name': 'Дані про характеристику товару',
            },
        ),
        migrations.CreateModel(
            name='ProductsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=200, verbose_name='Типи товару')),
                ('characteristic', models.ManyToManyField(to='catalog.productattributes', verbose_name='Характеристики товару')),
            ],
            options={
                'verbose_name': 'Типи товару',
                'verbose_name_plural': 'Типи товару',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Ціна')),
                ('discount', models.DecimalField(decimal_places=0, default=None, max_digits=10, verbose_name='Ціна зі знижкою')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Кількість товару')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productsbrand', verbose_name='Бренд')),
                ('img', models.ManyToManyField(to='catalog.productsimg', verbose_name='Зображення')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productstype', verbose_name='Тип товару')),
            ],
            options={
                'verbose_name': 'Товари',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.AddField(
            model_name='productattributes',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.valueproductattributes'),
        ),
    ]
