# Generated by Django 4.1.6 on 2023-03-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valueproductattributes',
            options={'verbose_name': 'Дані про характеристику товару', 'verbose_name_plural': 'Дані про характеристику товару'},
        ),
    ]
