# Generated by Django 4.1.6 on 2023-03-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=10, null=True, verbose_name='Ціна зі знижкою'),
        ),
    ]
