# Generated by Django 4.1.6 on 2023-03-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='procesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.valueproductattributes', verbose_name='процесор'),
            preserve_default=False,
        ),
    ]
