# Generated by Django 4.1.6 on 2023-04-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_products_battery_capacity_alter_products_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Текст відгуку')),
                ('author_name', models.CharField(default=None, max_length=200, verbose_name="Ім'я користувача")),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Кількість відгуків')),
                ('average_score', models.FloatField(default=0.0, verbose_name='Середня оцінка')),
                ('content', models.ManyToManyField(to='catalog.commentcontent', verbose_name='Деталі коментаря')),
            ],
        ),
    ]
