# Generated by Django 4.1.6 on 2023-04-04 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_commentcontent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.comment', verbose_name='Коментарі'),
        ),
    ]
