name: test_Django
on: [pull_request, push]
jobs:
  test_project:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: zergling
          MYSQL_DATABASE: mysql
        ports: ['3306:3306']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        run: cd TechnicStore && pip install -r requirements.txt
      
      - name: Run database migrations
        env: 
          DBENGINE: django.db.backends.mysql
          DBNAME: mysql
          DBUSER: root
          DBPASSWORD: zergling
          DBHOST: 127.0.0.1
          DBPORT: $
        run: cd TechnicStore && python manage.py migrate

      - name: Run tests
        env: 
          DBENGINE: django.db.backends.mysql
          DBNAME: mysql
          DBUSER: root
          DBPASSWORD: zergling
          DBHOST: 127.0.0.1
          DBPORT: $
        run: cd TechnicStore && python3 manage.py test